### ISSUE TITLE
Beta Test

### ISSUE THREAD

**Issue by suspiciouscow** [Plan-At/PlanAt-LandingPage#23]
Layout Issues and General Comments

The "Meet Our Staff" section images are squished. 
![image](https://user-images.githubusercontent.com/91506723/173487290-7128657b-b9a2-4702-9aa5-ae8e489b0cd5.png)

Kind of a personal preference thing but the very left image under "Latest News From The Blog" isn't aligned with the other two images and stood out to me. I think it would fit in better if it aligned with the other images especially since the other images on the website are aligned. Alternatively, the left image could be placed in the middle instead so it doesn't stand out as much.
![image](https://user-images.githubusercontent.com/91506723/173487596-692e8569-679b-4765-b516-62c3d0cd3596.png)

The select animation for the text under "Our Services" is a really nice touch and makes the website look very polished 👍
![image](https://user-images.githubusercontent.com/91506723/173487785-16e67ccb-f5de-4a3f-bbe7-86d300a0d02a.png)

Not sure if this was intentional but the plants at the top of the page made me think of the website name being a play on words for plant? It could be cool to add more plant themed images in the website if that's what you were going for.

**Comment by stewluj** [comment]
Thank you for your insights, Miki! I made sure to fix your issues. Closing now
